on:
  workflow_dispatch:
    inputs:
      websiteURL:
        description: "What Website Screen ?"
        required: true
        default: "https://tai-studio.netlify.app/"
      width:
        description: "What Website Width Size ?"
        required: true
        default: "1920"
      height:
        description: "What Website Height Size ?"
        required: true
        default: "1080"
name: Screen Website
jobs:
  render:
    name: Screen Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: npm install
      - run: npm run screen -- --props="$WORKFLOW_INPUT"
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - uses: actions/upload-artifact@v2
        with:
          name: screen
          path: screen.png
